sudo: required
services:
  - docker

before_install:
  - docker build -t william2772/blog-client -f ./daily-blog/Dockerfile.dev ./daily-blog

script:
  - docker run -e CI=true william2772/blog-client npm test

after_success:
  - docker build -t william2772/blog-client -f ./daily-blog/Dockerfile ./daily-blog
  - docker build -t william2772/blog-api -f ./api/Dockerfile ./api
  - docker build -t william2772/blog-nginx -f ./nginx/Dockerfile ./nginx
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD 
  - docker push william2772/blog-client
  - docker push william2772/blog-api
  - docker push william2772/blog-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Blog-env-migrated
  env: Blogenvmigrated-env
  bucket_name: elasticbeanstalk-us-east-2-571983945258
  bucket_path: Blog-env-migrated
  on:
    branch: master
  access_key_id: $AWS_ID
  secret_access_key: $AWS_PASSWORD