sudo: required
services:
  - docker

before_install:
  - docker build -t william2772/blog-client -f ./daily-blog/Dockerfile.dev ./daily-blog

script:
  - docker run -e CI=true william2772/blog-client npm test

after_success:
  - docker build -t william2772/blog-client -f ./daily-blog/Dockerfile ./daily-blog
  - docker build -t william2772/blog-api -f ./api/Dockerfile ./api
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD 
  - docker push william2772/blog-client
  - docker push william2772/blog-api