version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
  blog:
    environment: 
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./daily-blog
      dockerfile: Dockerfile.dev
    volumes: 
      - ./daily-blog:/app
      - /app/node_modules
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    
    